2023-08-14 10:05:34,742 INFO    MainThread:48087 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2023-08-14 10:05:34,742 INFO    MainThread:48087 [wandb_setup.py:_flush():76] Configure stats pid to 48087
2023-08-14 10:05:34,742 INFO    MainThread:48087 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-08-14 10:05:34,742 INFO    MainThread:48087 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntu/ai_dev/NST/text2svg/Font-To-Sketch/wandb/settings
2023-08-14 10:05:34,742 INFO    MainThread:48087 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-08-14 10:05:34,742 INFO    MainThread:48087 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-08-14 10:05:34,742 INFO    MainThread:48087 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'code/main.py', 'program': 'code/main.py'}
2023-08-14 10:05:34,742 INFO    MainThread:48087 [wandb_init.py:_log_setup():507] Logging user logs to /home/ubuntu/ai_dev/NST/text2svg/Font-To-Sketch/wandb/run-20230814_100534-yt6czoxo/logs/debug.log
2023-08-14 10:05:34,742 INFO    MainThread:48087 [wandb_init.py:_log_setup():508] Logging internal logs to /home/ubuntu/ai_dev/NST/text2svg/Font-To-Sketch/wandb/run-20230814_100534-yt6czoxo/logs/debug-internal.log
2023-08-14 10:05:34,743 INFO    MainThread:48087 [wandb_init.py:init():547] calling init triggers
2023-08-14 10:05:34,743 INFO    MainThread:48087 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'parent_config': 'baseline', 'save': {'init': True, 'image': True, 'video': True, 'video_frame_freq': 1}, 'trainable': {'point': True}, 'lr_base': {'point': 1}, 'lr': {'lr_init': 0.002, 'lr_final': 0.0008, 'lr_delay_mult': 0.1, 'lr_delay_steps': 100}, 'num_iter': 500, 'render_size': 600, 'cut_size': 512, 'level_of_cc': 1, 'seed': 42, 'diffusion': {'model': 'runwayml/stable-diffusion-v1-5', 'timesteps': 1000, 'guidance_scale': 100}, 'loss': {'use_sds_loss': True, 'tone': {'use_tone_loss': True, 'dist_loss_weight': 200, 'pixel_dist_kernel_blur': 201, 'pixel_dist_sigma': 10}, 'conformal': {'use_conformal_loss': True, 'angeles_w': 0.5}}, 'config': 'code/config/base.yaml', 'experiment': 'default', 'font': 'ArefRuqaa-Regular', 'semantic_concept': 'music', 'word': 'موسيقى', 'letter': 'ArefRuqaa-Regular_موسيقى_scaled', 'script': 'arabic', 'caption': 'a music. minimal flat 2d vector. lineal color. trending on artstation', 'log_dir': 'output/arabic', 'optimized_letter': 'موسيقى', 'batch_size': 1, 'token': '', 'use_wandb': 1, 'wandb_user': 'none', 'target': 'code/data/init/ArefRuqaa-Regular_موسيقى_scaled', 'experiment_dir': 'output/arabic/موسيقى_music_42'}
2023-08-14 10:05:34,743 INFO    MainThread:48087 [wandb_init.py:init():596] starting backend
2023-08-14 10:05:34,743 INFO    MainThread:48087 [wandb_init.py:init():600] setting up manager
2023-08-14 10:05:34,746 INFO    MainThread:48087 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-08-14 10:05:34,747 INFO    MainThread:48087 [wandb_init.py:init():606] backend started and connected
2023-08-14 10:05:34,760 INFO    MainThread:48087 [wandb_init.py:init():697] updated telemetry
2023-08-14 10:05:34,771 INFO    MainThread:48087 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-08-14 10:05:34,875 ERROR   MainThread:48087 [wandb_init.py:init():756] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-08-14 10:05:34,926 ERROR   MainThread:48087 [wandb_init.py:init():1165] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/ldm/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1147, in init
    run = wi.init()
  File "/home/ubuntu/.conda/envs/ldm/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 762, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-08-14 10:05:35,928 WARNING MsgRouterThr:48087 [router.py:message_loop():77] message_loop has been closed
